### PR TITLE
LPS-110757 SF

### PR DESCRIPTION
**Pull request by LuismiBarcos**

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by LuismiBarcos** [comment]
ci:stop

**Comment by LuismiBarcos** [comment]
Pull request submitted to [brianchandotcom#86767](https://github.com/brianchandotcom/liferay-portal/pull/86767)

**Comment by LuismiBarcos** [comment]
Merged

**Pull request closed without merging**
