### PR TITLE
LPS-110265 Fix checking permissions to post new questions to a category

### PR DESCRIPTION
**Pull request by javierdearcos**

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
Having some doubts about if the "context.canCreateThread" old condition should be also checked to create a new thread in the category...

**Comment by LuismiBarcos** [comment]
ci:stop

**Comment by LuismiBarcos** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by LuismiBarcos** [comment]
Pull request submitted to https://github.com/LuismiBarcos/liferay-portal/pull/14. [See changes here.](https://github.com/LuismiBarcos/liferay-portal/compare/ef3f22b0c23b~2...ef3f22b0c23b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
