### PR TITLE
LPS-110847 Hide category subscribe button when the user does not have category subscription permission

### PR DESCRIPTION
**Pull request by javierdearcos**

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by LuismiBarcos** [comment]
ci:stop

**Comment by LuismiBarcos** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by LuismiBarcos** [comment]
Pull request submitted to https://github.com/LuismiBarcos/liferay-portal/pull/14. [See changes here.](https://github.com/LuismiBarcos/liferay-portal/compare/ef3f22b0c23b~2...ef3f22b0c23b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
