### PR TITLE
Lps 147060

### PR DESCRIPTION
**Pull request by lawrence-lee**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
@LuismiBarcos , could you look into these test failures?

**Comment by lawrence-lee** [comment]
once you have fixed the tests, you can run `gw installCache` then `gw test -Pproject.templates.test.builds=true` to run the test locally. otherwise you can commit the changes from `gw installCache` and have it tested in ci like I did here https://github.com/LuismiBarcos/liferay-portal/pull/25#issuecomment-1049004174

**Comment by LuismiBarcos** [comment]
Sent [here](https://github.com/LuismiBarcos/liferay-portal/pull/26)

**Pull request closed without merging**
