### PR TITLE
LPS-110848 Hide Post Answer text area and button to users without reply to message permission

### PR DESCRIPTION
**Pull request by javierdearcos**
May be the context.canCreateThread condition is still needed... If not it would be possible to remove this property and make some clean up

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by LuismiBarcos** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by LuismiBarcos** [comment]
Pull request submitted to https://github.com/LuismiBarcos/liferay-portal/pull/14. [See changes here.](https://github.com/LuismiBarcos/liferay-portal/compare/ef3f22b0c23b~2...ef3f22b0c23b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
