### PR TITLE
LPS-147060 Update blade command to generate rest modules templates

### PR DESCRIPTION
**Pull request by LuismiBarcos**

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
ci:test:project-templates

**Comment by LuismiBarcos** [comment]
ci:reevaluate:1367401_579

**Comment by LuismiBarcos** [comment]
ci:test:project-templates

**Comment by magjed4289** [comment]
Reviewed. This pull contains no unique failures. ✔️
Ok to manually forward.

**Comment by LuismiBarcos** [comment]
Hi @lawrence-lee 
Sorry to bother you again. 
I fixed the tests and review all the changes for Gradle and Maven. 
The tests pass in Local and the CI fails are not related to our changes. is it ok to send it to Brian or is it necessary some additional steps?

**Comment by lawrence-lee** [comment]
Hi @LuismiBarcos , 
I dont see any fixes for the tests. The way the tests work, you need to run `gw installCache` and commit that as `FAKE GRADLE CACHE`. The tests rely on these created artifacts to test. Otherwise the tests are running against the artifacts that come from nexus.

**Comment by LuismiBarcos** [comment]
I'm trying again. I think it was my fault because I only did `gw installCache` just over `project-templates-rest-builder` 😓

**Comment by LuismiBarcos** [comment]
ci:test:project-templates

**Comment by LuismiBarcos** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
Hi @LuismiBarcos , See https://github.com/LuismiBarcos/liferay-portal/pull/27#issue-1159771073

**Comment by LuismiBarcos** [comment]
Hi @lawrence-lee 
Sorry for not responding to this #27 last week 😞 
I'm trying again here (I already rebase de changes to master) 
Also, I think that we could send this if it fails because the errors that I am getting seem not to be related. Also, a member of QA review it and said that it is safe to send it to Brian.

I don't know if after this I can send it or it is necessary for any additional step.
Thanks again for your help.

**Comment by lawrence-lee** [comment]
The problem is not just a rebase, but you need to re-run the tasks. You should look at the other PR for the test failures. The way the project templates work is quite complicated because it requires an updated cache. The cache in this branch is not correct.

**Comment by LuismiBarcos** [comment]
I also regenerate the commit "FAKE GRADLE CACHE" executing `gw installCache` in `modules/sdk/projects-templates`
That should fix it, right?

**Comment by lawrence-lee** [comment]
What i would do is a `git reset --hard da91817c4977a64efb11e5ba0513b27cf48a6a2a` and then in `modules/sdk/project-templates`  run `gw installCache updateFileVersions`

Then you should see the test failure when you go to `project-templates-rest-builder` and run `gw test -Pproject.templates.test.builds=true`. You should see the same test failures as in this https://github.com/LuismiBarcos/liferay-portal/pull/27#issuecomment-1059366193

Let me know if you dont see it.

**Comment by LuismiBarcos** [comment]
Yes, I see the test failures now. I will take a look.
Thanks again

**Comment by LuismiBarcos** [comment]
ci:test:project-templates

**Comment by LuismiBarcos** [comment]
ci:test:project-templates

**Comment by javierdearcos** [comment]
ci:test:project-templates

**Comment by LuismiBarcos** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by javierdearcos** [comment]
ci:test:project-templates

**Comment by javierdearcos** [comment]
The failures are related with the Service Builder template and not with the REST Builder that we are changing.

Can we send the PR directly to Brian @lawrence-lee?

**Comment by lawrence-lee** [comment]
@javierdearcos @LuismiBarcos , yes if `ci:test:relevant` finishes then it can fwd to Brian

**Comment by javierdearcos** [comment]
thank you!

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
Rebased to master and regenerated the gradle cache and las project-templates

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
ci:forward

**Pull request closed without merging**
